routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return redirect('/login');
});

Route::get('/login', 'LoginController@index');
Route::post('/login','LoginController@login');

Route::group(['middleware'=>'role'], function(){    

    Route::resource('/authors','AuthorController');
    
    Route::resource('/books','BookController');
    
    Route::get('/logout','LoginController@logout');
});

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Traits\ApiTrait;
use Carbon\Carbon;

class AuthorController extends Controller
{
    use ApiTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()    {
        
        $authors = $this->getAuthors("id","ASC",$limit = 25,$page = 1);
        
        $author_list = [];
        foreach($authors['items'] as $author){
            $count = count($this->getAuthor($author['id'])['books']);
            $author['book_count'] = $count;
            array_push($author_list,$author);
        }
        return view('pages.author.index')->with('authors',$author_list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $birthday = Carbon::createFromFormat('Y-m-d H:i:s', $request->birthday.' 00:00:00');
        

        $author = array("first_name" => $request->first_name,
                        "last_name" => $request->last_name,
                        "gender" => $request->gender,
                        "birthday" => $birthday->toAtomString(),
                        "biography" => $request->biography,
                        "place_of_birth" => $request->place_of_birth
        );

        $res = $this->addAuthor(json_encode($author));

        if($res == 200){
            session()->flash('message', 'Author created!');
        }else{
            session()->flash('error_message', 'Failed to add author!');
        }
        return redirect('/authors');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = $this->getAuthor((integer) $id);
       
        return view('pages.author.show')->with('author',$author);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        
        $res = $this->deleteAuthor((integer) $id);

        if($res == 204){
        session()->flash('message', 'Successfully deleted!');
        }else{
        session()->flash('error_message', 'Fail to delete author!');        
        }
        return redirect('/authors');
    }
}

resources/views/pages/author/index.blade.php
@extends('template.master')

@section('content')
<div class="author">
    <div class="row">
        <div class="col-lg-8">
             <h1>Author</h1>
        </div>
        <div class="col-lg-4">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addauthor"style="float:right" >add new author</button>
                
                    <!-- The Modal -->
                <div class="modal" id="addauthor">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <form class="form-horizontal" method="POST" action="{{ route('authors.store')}}">
                            {{ csrf_field() }}
                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Add New Author</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="first_name">First Name</label>
                                        <input type="text" name="first_name" class="form-control" placeholder="Enter First Name" id="first_name" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="last_name">Last Name</label>
                                        <input type="text" name="last_name" class="form-control" placeholder="Enter Last Name" id="last_name" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="last_name">Gender</label>
                                        <br>
                                        <div class="form-check-inline">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" value="male" name="gender" checked>Male
                                        </label>
                                        </div>
                                        <div class="form-check-inline">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" value="female" name="gender">Female
                                        </label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="birthday">Birthday</label>
                                        <input type="date" name="birthday" class="form-control"  id="birthday" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="biography">Biography</label>
                                        <textarea name="biography" id="biography" class="form-control" cols="5" rows="5" required></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="place_of_birth">Place of Birth</label>
                                        <input type="text" name="place_of_birth" class="form-control" placeholder="Enter Place of Birth" id="place_of_birth" >
                                    </div>

                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">                                    
                                    <button type="submit" class="btn btn-primary">Add</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> 
        </div>
    </div>
    <table id="author_list" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Birthday</th>
                <th>Gender</th>
                <th>Place of Birth</th>
                <th>Action</th>
            </tr>
        </thead>
       <tbody>
            @foreach($authors as $author)
            <tr>
                <td><a href="/authors/{{ $author['id'] }}">{{ $author['first_name'].' '.$author['last_name'] }}</a></td>
                <td>{{ date('M-d-Y', strtotime($author['birthday'])) }}</td>
                <td>{{ $author['gender'] }}</td>
                <td>{{ $author['place_of_birth'] }}</td>
                <td >
                <form action="{{ route('authors.destroy', $author['id'])}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit" {{ $author['book_count'] != 0? 'disabled':'' }} ><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="Book Count : {{ $author['book_count'] }}"></i></button>
                </form></td>
            </tr>
            @endforeach
       </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Birthday</th>
                <th>Gender</th>
                <th>Place of Birth</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>

@endsection

@section('custom_js')
<script>
    
$(document).ready(function () {
    var table = $('#author_list').DataTable();
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
@endsection

resources/views/pages/author/show.blade.php
@extends('template.master')

@section('content')
    <div class="container-fluid">
        <b>Author</b> : {{ $author['first_name'].' '.$author['last_name'] }} <br>
        <b>Birthday</b> : {{ date('M-d-Y', strtotime($author['birthday'])) }}<br>
        <b>Gender</b> : {{ $author['gender'] }}<br>
        <b>Place of Birth</b> : {{ $author['place_of_birth'] }}<br>
        <b>Biography</b> <br>
        <p>
            {{ $author['biography'] }}
        </p>
    <br>
    <div class="row">
        <div class="col-lg-8">
             <h1>Books</h1>
        </div>
        <div class="col-lg-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addbook" style="float:right">add new book</button>

            <div class="modal" id="addbook">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <form class="form-horizontal" method="POST" action="{{ route('books.store')}}">
                            {{ csrf_field() }}
                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Add New Author</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <input type="hidden" name="author" value="{{ $author['id'] }}">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" name="title" class="form-control" placeholder="Enter Title" id="title" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="release_date">Release Date</label>
                                        <input type="date" name="release_date" class="form-control"  id="release_date" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description" id="description" class="form-control" cols="5" rows="5" required></textarea>
                                    </div>                                 
                                    <div class="form-group">
                                        <label for="isbn">ISBN</label>
                                        <input type="text" name="isbn" class="form-control" placeholder="Enter ISBN" id="isbn" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="format">Format</label>
                                        <input type="text" name="format" class="form-control" placeholder="Enter Format" id="format" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="number_of_pages">Number of Pages</label>
                                        <input type="text" name="number_of_pages" class="form-control" placeholder="Enter Number of Pages" id="number_of_pages" required>
                                    </div>

                                    

                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">                                    
                                    <button type="submit" class="btn btn-primary">Add</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> 
        </div>
    </div>
    <table id="author_book_list" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Title</th>
                <th>Release Date</th>
                <th>Description</th>
                <th>ISBN</th>
                <th>Format</th>
                <th># of Pages</th>
                <th>Action</th>
            </tr>
        </thead>
       <tbody>
            @foreach($author['books'] as $book)
            <tr>
                <td>{{ $book['title'] }}</td>
                <td>{{ date('M-d-Y', strtotime($book['release_date'])) }}</td>
                <td>{{ $book['description'] }}</td>
                <td>{{ $book['isbn'] }}</td>
                <td>{{ $book['format'] }}</td>
                <td>{{ $book['number_of_pages'] }}</td>
                <td><form action="{{ route('books.destroy', $book['id'])}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit"><i class="fas fa-trash"  ></i></button>
                </form></td>
            </tr>
            @endforeach
       </tbody>
        <tfoot>
            <tr>
                <th>Title</th>
                <th>Release Date</th>
                <th>Description</th>
                <th>ISBN</th>
                <th>Format</th>
                <th># of Pages</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>
    </div>
@endsection

@section('custom_js')
<script>
    
$(document).ready(function () {
    var table = $('#author_book_list').DataTable();
});
</script>
@endsection